version: "2"
checks:
  method-lines:
    enabled: true
    config:
      threshold: 100
  method-complexity:
    config:
      threshold: 10
plugins:
  eslint:
    enabled: true
    channel: eslint-4
    config: .eslintrc.yaml
  fixme:
    enabled: true
  git-legal:
    enabled: true
  shellcheck:
    enabled: true
exclude_patterns:
- "**/node_modules/"
- "packages/**/dist/"
- "packages/**/docs/"
- "packages/**/test/"
