extends:
- eslint:recommended
- plugin:react/recommended
- plugin:import/react
rules:
  no-useless-escape: 1
  eqeqeq: 2
  react/no-find-dom-node: 0
  semi: 2
  react/prop-types:
  - 2
  - ignore:
    - children
  quotes:
  - 2
  - double
  import/named: 2
  import/export: 2
  import/no-mutable-exports: 2
  import/first: 2
  import/no-duplicates: 2
  import/no-unresolved:
  - 2
  - commonjs: true
    ignore:
    - "@randy\\.tarampi\\/\\w+"
  import/default: 2
  react/no-unescaped-entities: 0
  no-global-assign:
  - 2
  - exceptions:
    - __CAMPAIGN_SOURCE__
    - __CAMPAIGN_MEDIUM__
    - __CAMPAIGN_NAME__
    - __CAMPAIGN_TERM__
    - __CAMPAIGN_CONTENT__
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
env:
  node: true
  es6: true
  browser: true
  mocha: true
globals:
  Promise: true
  __ASSET_URL__: false
  __RESUME_ASSET_URL__: false
  __LETTER_ASSET_URL__: false
  __APP_URL__: false
  __CODE_APP_URL__: false
  __WORDS_APP_URL__: false
  __POSTS_APP_URL__: false
  __PHOTOS_APP_URL__: false
  __RESUME_APP_URL__: false
  __LETTER_APP_URL__: false
  __PHOTOS_SERVICE_URL__: false
  __WORDS_SERVICE_URL__: false
  __POSTS_SERVICE_URL__: false
  __RESUME_SERVICE_URL__: false
  __LETTER_SERVICE_URL__: false
  __PUBLISHED_RESUME_URL__: false
  __PUBLISHED_LETTER_URL__: false
  __CAMPAIGN_SOURCE__: false
  __CAMPAIGN_MEDIUM__: false
  __CAMPAIGN_NAME__: false
  __CAMPAIGN_TERM__: false
  __CAMPAIGN_CONTENT__: false
plugins:
- react
- import
settings:
  import/resolver:
    node:
      extensions:
      - .js
      - .jsx
      - .json
