language: node_js
dist: trusty
node_js:
- '8'
env:
  matrix:
    - PACKAGE=css
    - PACKAGE=js
    - PACKAGE=pseudoimage
    - PACKAGE=pseudolocalize
    - PACKAGE=jsx
    - PACKAGE=posts
    - PACKAGE=blog
    - PACKAGE=photos
    - PACKAGE=words
    - PACKAGE=web
    - PACKAGE=resume
  global:
    - secure: ZTBYFZ10aI9BZPy5svRBilIqEbx88fLxUVgblqhlWStF8jhnWslOULzjXFbz2dpTboEYDxlFwfo9+K0hYUJmL7iDtpnKX9pbA5SXQxok2W9zoGGrNDedcXIQxyCWMKKmpcco5B6PFS+uScuYSQzUu9FEwkcEXoxr1hUom2THEXm3FxRHMP5iCr9HwNb0ZmHq622G5jEtCImWErHauLYyuay9A9geFysHuUE5qNITsQP5IjNH2vEqs3KAGZxLAUbV7OKwafEh2mPDqYV/96uOf4uGtQA5EV2yfoemkLN1OgffGGLoPqdL5kDzkcrPacbVvQSc8pL5T4irsNOngs3PsiEtz21qdkA0o9pwsbmC4HWRxq/4A86ECH1mWoLXp6aF6LmUpxclnQIj46986Dm+DSfg9wmUHP4WJsfrQOfJ4ZIgtAG0hS5nKSHY9qep9bkLNgP4K6ZCVosUG3QgA5nImyP++90H8eM6hzNCpXCBX71S1QmW6iQqPT1B34S2fJzPQYU3mFX05itP7V9ikKsFXy9YDjmzc8f1E09/WH1bJcW/4kcHUxyki6PZy4hWM7252H7iI1wcseOExzmS9awkZUKyGqVrVQ9D7/KZxmh9zHfRHXRZj1FSDtLBaPSlAS8Do0EDToFpUsFEdHUyvgf3QWg6jwweS9zXlXTmKxBPxz8=
before_install:
- uname -a
- lscpu
- npm install -g npm
- export NODE_ENV=prd;
after_install:
- git config --local user.name "Travis"
- export TRAVIS_AUTHOR=travis@randytarampi.ca
- export COMMIT_AUTHOR=`git --no-pager show -s --format='%ae' \`git rev-parse\``
- git config --local user.email $TRAVIS_AUTHOR
- git config --local branch.autosetuprebase always
#before_script:
#- export PATH=`echo $PATH | sed -re 's/:?\.\/node_modules\/\.bin:?//g'`
script: ./bin/split.sh $PACKAGE
#after_script:
#- git checkout master;
#- ls -al;
#- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG};
notifications:
  slack:
    secure: YdWidvVw0Guj6iPXO/Y2wJ+h6as9CU7brL4crIKHCOZjH4ffXI63r6tuKAE+y9zJpAp1NntdeVWdZAe7eMPqZcRGg1HybzLf8aEQkBFK8tf/q2zU93DVFCjrDJDF5lqY4ySTe5aSvC8Q7M1167+PLpZy5H8aUlj0kSzJ/FGOfeI93p07Wtviv8cN6nZ986q90Djovkfn9tuaRj6fR6MjWlFcQ/9UNhpVqf8aGXjE1AOHYth6k7L4YWULWb3Don1oW2wFX/E4rGecqWBKyh7VN742va1y0VHaLys+bbGbmIUQllESVy4gFyAXs/tZjx47+sXn2R6nJn5Y9kIsMe0GKBlGhV0N5QoOjVbJt8xNVgF8HzRHEoo5uDZpd5tFbFa4rK1ZvtV+mmIvjqXtKxjuQ+AXcmdCuORaN0y6He63TF66uMfdoF75aatr0ebT2Ma9/NTMdg3L7MWfiCAOl0y1a/8l9HSOv01ZL2m3iAotB+F231ZouofDuOmsSxAhDJGwskQkrExoU/t8JW4jz391sbQpGmJBDSMyFKe6EZwXqV6R9OfoWxbEXRNz7ZEKNZG5d/EUo+BRNL35MsCy2fnM41pPUHE1jf6YnnMbZtKF5DhR8LA5R3RlrSdUuM2T0JNJxK08prLz8RgghlKpsNEYxomqagqQnQd1+4TVK7A37WY=
