language: node_js
dist: trusty
node_js:
- '8'
env:
  global:
  - CXX=g++-4.8
  - secure: i+0iScbWJMYzZmE+PJIXmsz9LzWWQGJ3mEpzcC0AWpxqhhVs06Nu6B2bNA5pOzssciy1NNt5IVFaC7I34EhA2EYBUhSY1APThf1fal0q/APZAnGKiFN9ZKchYa9wzfnf/VZo/lsPPjV+JX9ZAtd+LNALONiFYymkKCxDQsxZl2Rqc048Q811AtPPlk4cR0gwMVm1grkKyx4ujTKkLhpjYhmxXZa8esi/bT88qmu66ELX1GCWyADKjIFBq1p0EnDLL0WV6ovwo1fOffoeRQ7YKGfjRxeujBM3GA3bAJIgk1KTEKuvJDGptZU+3FA4W6FEpaW1HEqXr15SzOb81cJPoSvPB+9VzUXDPydY0WZmOCQN/03LPjFP+/6bm0NfQUstHh4kSoXdhjHg88YIOBoHfeksEcf3b2AbHmuxiBJ2V4lrOdyFUjG10r4k17tHjGKmPvxnoxv647dkQwwaPBGLEnNlH+eftQ8GcSptvIgEae4b0R+f6YClbDcmFagzsXo8e9q0sfW6uRjtsboC9agVSHhNhhdROIq4/f8mfWiyswr+cFBEc25Fy9ca1OGAxtj8g+sl9wUB5mzNAmKbgg8FRSIVCTFqtcmKVPOW2i/I9DTAx/ZXfYB48hm1stUX7nX6WuZwSh60493mSL352SRsxk0DmcICVJxD81AzNRTeC3Y=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- uname -a
- lscpu
- touch .env
- npm i -g npm
- npm install -g serverless
- if [ -z "$TRAVIS_TAG" ]; then
    export NODE_ENV=dev;
  else
    export NODE_ENV=prd;
  fi;
install: npm ci
script: npm run travis
after_success:
- mkdir -p ../dpl_cd_upload
- tar -zcf ../dpl_cd_upload/me.photos.tar.gz -C ./ .
- git config --local user.name "Travis"
- export TRAVIS_AUTHOR=travis@randytarampi.ca
- export COMMIT_AUTHOR=`git --no-pager show -s --format='%ae' \`git rev-parse\``
- git config --local user.email $TRAVIS_AUTHOR
- if [ -z "$TRAVIS_TAG" ]; then
    if [ "$COMMIT_AUTHOR" != "$TRAVIS_AUTHOR" ]; then
      npm version minor;
      git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} --tags;
      npm version preminor -m "[Travis] Prepare version %s";
      git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} HEAD:master;
    fi;
  fi;
deploy:
  provider: script
  script: npm run deploy
  on: &2
    tags: true
    branch: master
notifications:
  slack:
    secure: XIKwYs484VwJNLD4IuJz/aApirGz98J2LS10EqorZ6d7hjavq4BTctb2m1LAgpONdeZNaFjZvoQpy4KvkyPFXCewKv0NwmMdcb7Ae89EQNqYypE/X0XhGGgd9JBtCbFjreokVflIvkrigPPmllJGNIngjfhquw/u11NaKXQkrdQ62+hcBOkj3uPXsXZUG++QuSpJy0fFm8usuDWjIcJCxI2e1XjAGgN4me4t5Yn/MzGqROGdj/PLWJnx8mA37EEd2aIGckFt+8SdfPhMNvh2LF5HKD4QWdVAbSXvDf/JUPR1R1FIviv3yF9U0Pm7/rNMR3jxK9BWsnbX6K+6mxf9z4uqGgzbpl8/PW+MtpeyytmGmhiT8wzOaL45GOKcnKrVKEeD+g2Aub3j64eiN84+w0EfWqPazn5C+AxeJ18QkSXREWgQDSsW6qCJO6X2jjcm0H+IcqFeVOPk1quTlfgmRj2B0bZmLlvn72he+ym8GL03u+2X7liMk4rnk6UCqsG8whGR6NHVVzGT6MSL2xBbTfi/tBTgeVGKUZm2y0zGJcXbBENzhPOWMfp9fCL7trEfry2HhfKG3Jt8dQMYrl95qesV6UgKI/vAFR8SBOPR9HWJP/SJi3mPe46JbYOKL7iZxyr7c5Hjjt86z8Jz5NiXf6b1AI+QKWf+2o3N5PaKWbQ=
