language: node_js

node_js:
- '6'

env:
- CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
- touch .env

script: npm run travis

before_deploy:
- touch .env
- mkdir -p ../dpl_cd_upload
- tar -zcf ../dpl_cd_upload/me.words.tar.gz -C ./ .

deploy:
- provider: s3
  access_key_id: AKIAIIJQMCB7NWCX5LNA
  secret_access_key: &1
    secure: ZoS4OSWOsVT/t5AyC4FxBt01fI0s2ikF7oxjr83n5stJOidAwlYqGYymYw7QRNiKIKEF/NSxn4J+rDMae7tvF7sOYBxOpwLxYwAb8Xr6G98cLnxYXbGVHjDyijuvzaT/KrSW92wJpuYeZyx6bjknUcTfpjgy/kH+pp4jwqA8ManiDHxOY+1BoHEFTM6bOJdyIWcDcg9YYvHuOD6Qblhq7/P8K47j1f2Uux8HQo7EI0owFChxy0jqQ0My+QlQgHVc3lui/NmWYCtOzTuzJCCtZH57a9yi6a9l5txjY8TS+KTrhCh9V+2Q1YnDB9ZPD3IQ+Qlnkd8hRDb/E0l4vxGDaXtF7kAqIu0xtnNucPBqhN5iEnhpSpsW4bTVerXag+b/yjKYUmpq598dSb2hPIPvr0Ithhc1OLSacvhCYvgbUj/NkeDaUzCAMYdVnFhvGYUnUPsG/UUCtd6MCj9va7dLrYbAV0UnfgI0TZuTpBH8AS4G5N6thyRLQGlNpbp3FxlmVG0mfEXB/i6Pdu05UtqNxMKTgLqvsMf625udKt65mRTAqv55Jxj5DqoEvf5Dzx1tvC3j4nwHm0eKcVAcrBTgtt2tYRGDOtkE8G/FY3qEJayrm9ohZaj2C7MC34zkSVsyMqmdgC14g6i2x6JsZ8UULSwhZCi91pAI27f+GbWOwhs=
  skip_cleanup: true
  on: &2
    repo: randytarampi/me.words
    branch: master
  bucket: randytarampi-releases
  region: eu-west-1
  detect_encoding: true
  local-dir: ../dpl_cd_upload
- provider: codedeploy
  access_key_id: AKIAIIJQMCB7NWCX5LNA
  secret_access_key: *1
  bucket: randytarampi-releases
  key: me.words.tar.gz
  bundle_type: tgz
  application: me.words
  deployment_group: web
  on: *2
  wait-until-deployed: true
  region: eu-west-1
