language: python
python:
- '3.5'
env:
- CXX=g++-4.8 TRAVIS_NODE_VERSION=6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- touch .env
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
install:
- pip install -r requirements.txt
- npm install
script: echo "Lol. Just straight up deploying..."
before_deploy:
- touch .env
- mkdir -p ../dpl_cd_upload
- tar -zcf ../dpl_cd_upload/me.blog.tar.gz -C ./ .
deploy:
- provider: s3
  access_key_id: AKIAI3EMH5UQ2CYHR3SA
  secret_access_key: &1
    secure: hZ/yQMJFWwFCqp67c4fysofF9Iz5Fs1tl9ckP+CPR6jWdXrSjvEwV+d83EyK2ExCC0LNolYKZLpCNZmyfRlSkwE2Bo8Pf6x63WNzTCBMMLjpup1H1sUvG1X0BEC2pp76GkoSoLd2LQSSJUTrYlDIzue8hgGmrr/pszGyNUJwoRAfm1LM3UkHFCYC9WmlZnqYZT8IUzxMcQ1+rGqkbgd6AcQPCb7UdMbzJntHqE1yYnQhJlMTzKg4ZxIsIUS+qHfihzyt2ocBTii0THQ8BnNt4W1B5bcc2l3IBf0bf2ZwNSrAXJy6sX9/+9aR+3N3bXA05mdUFy08klOpKENZGnA9QIxGydjT1KrRV6OE+Y6qIzypJm0rAmQMx+tQtJ5O5BUw2U3jevUSurnjuIEPwWwvBisRMKbEEu7Aeuu7bMJ0HkdwGpWzUl6NesyfrcbKLQFioWUEpUfTMOUvt3ytdPZQ3BbaX3OE5Ty0oORbfh6zecBk0M5jdZWwN47+HvZN+J+w87K+BTh67qHmpoQDYNx+1tzttQ9k2rbizui3zetqtrv7OLoi2Ya/AobLacYp+vvdZ3fjgquZsbhuEJrdIMMM1E8LzfcrzXbCrJMEAQIkGIPt03t9bqdPtYNZcZp3tZcvhzNAIYTPj2qX8TwHpOSzSZ3hs3wiOB1V9WV11F5YVaw=
  skip_cleanup: true
  on: &2
    repo: randytarampi/me.blog
    branch: master
  bucket: randytarampi-releases
  region: eu-west-1
  detect_encoding: true
  local-dir: "../dpl_cd_upload"
- provider: codedeploy
  access_key_id: AKIAI3EMH5UQ2CYHR3SA
  secret_access_key: *1
  bucket: randytarampi-releases
  key: me.blog.tar.gz
  bundle_type: tgz
  application: me.blog
  deployment_group: web
  on: *2
  wait-until-deployed: true
  region: eu-west-1
notifications:
  slack:
    secure: wcPjg9yq8eMkkec9AMsl7wnT4jvyZH9dHgdv5eWCo5F4L0T/3tsznI7C2kmsyeDpveLvDdovnqoU6Jvd+OThPPF74btI5MRz6yw3G3YMv77aTON1HGSN4QHjdIM2P16Ug5qYkZeL94QfXknNX4xUb+fBdb2vphMYPjVPIkwfBF9eV07EPR/MZbv29DKxzST6rx/CP5inZZPl9zEsPdcJQory+A5q3RkGRXGjCz4GhjweDy0ywoQQ85EKfiyOke6I6XhCY15ZPh0HYHIFy8lsJZfIVRsWNXY1twCKLX3v+iB3o8POFgICQV+HMCc4J+Q4BAVe02uZtghwOZvmL4+ShrZijNFMn0KXUxOXnM0p3n08icIasIpGNwZswOC5kJ/iUh0wjI12fGVLCVwOWpclaoIskJDSF0BLTyB0p48CUjYPO1+8nzIC1Llz072r2p8ZO79eAK7O0MoxknEkEKwfH65XcsSID0Kc7zjR7AE1InsNmnDFcrogJnUh1zOHXcRrk84TTKsdaNSl4/a5plGkmC3BQfUJHcawYpI1VRy2bKmCP6U4kxQNejvMKsuyW7rPHmE/msSwvDHgq2bX4O9Nloqg+3Q35rWA/lftlBZts8wTFM/YkRm3Xsssiee39dtUV7NU+u+RuWPx23Z/rYGB886X8O+QoktTjhoVRvNjIvs=
