language: node_js
dist: trusty
node_js:
- '10'
- '8'
- '6'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '6'
  - node_js: '10'
env:
  global:
  - NODE_ENV=test
  - secure: ZTBYFZ10aI9BZPy5svRBilIqEbx88fLxUVgblqhlWStF8jhnWslOULzjXFbz2dpTboEYDxlFwfo9+K0hYUJmL7iDtpnKX9pbA5SXQxok2W9zoGGrNDedcXIQxyCWMKKmpcco5B6PFS+uScuYSQzUu9FEwkcEXoxr1hUom2THEXm3FxRHMP5iCr9HwNb0ZmHq622G5jEtCImWErHauLYyuay9A9geFysHuUE5qNITsQP5IjNH2vEqs3KAGZxLAUbV7OKwafEh2mPDqYV/96uOf4uGtQA5EV2yfoemkLN1OgffGGLoPqdL5kDzkcrPacbVvQSc8pL5T4irsNOngs3PsiEtz21qdkA0o9pwsbmC4HWRxq/4A86ECH1mWoLXp6aF6LmUpxclnQIj46986Dm+DSfg9wmUHP4WJsfrQOfJ4ZIgtAG0hS5nKSHY9qep9bkLNgP4K6ZCVosUG3QgA5nImyP++90H8eM6hzNCpXCBX71S1QmW6iQqPT1B34S2fJzPQYU3mFX05itP7V9ikKsFXy9YDjmzc8f1E09/WH1bJcW/4kcHUxyki6PZy4hWM7252H7iI1wcseOExzmS9awkZUKyGqVrVQ9D7/KZxmh9zHfRHXRZj1FSDtLBaPSlAS8Do0EDToFpUsFEdHUyvgf3QWg6jwweS9zXlXTmKxBPxz8=
cache:
  timeout: 1200
  directories:
  - $HOME/.npm
  - node_modules
  - packages/posts/node_modules
before_install:
- export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
- export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}
- uname -a
- lscpu
- npm install -g npm
before_script:
- npx lerna run pretest
script:
- npm run travis
after_script:
- npm run coveralls
stages:
- name: Test
  if: tag IS blank AND NOT commit_message ~= /(?:^release\(travis\):)/
- name: Deploy (dev)
  if: tag IS blank AND type = push AND branch = master AND NOT commit_message ~= /(?:^release\(travis\):)/
- name: Release
  if: tag IS blank AND type = push AND branch = master AND NOT commit_message ~= /(?:^release\(travis\):)/
- name: Deploy (prd)
  if: tag IS present
jobs:
  include:
  - stage: Release
    name: GitHub
    node_js: '8'
    env:
    - NODE_ENV=prd
    install:
    - git checkout $TRAVIS_BRANCH
    - npm run postinstall
    before_script: skip
    script: skip
    after_script: skip
    before_deploy:
    - mkdir -p $TRAVIS_BUILD_DIR/../dpl_cd_upload
    - tar -zcf $TRAVIS_BUILD_DIR/../dpl_cd_upload/me.tar.gz -C $TRAVIS_BUILD_DIR/ $TRAVIS_BUILD_DIR
    - git config --local user.name "Travis"
    - export TRAVIS_AUTHOR=travis@randytarampi.ca
    - export COMMIT_AUTHOR=`git --no-pager show -s --format='%ae' \`git rev-parse\``
    - git config --local user.email $TRAVIS_AUTHOR
    - git remote add ci-push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    - 'npx lerna publish --conventional-commits --yes --skip-npm --message "release(travis): Release %s." --git-remote ci-push'
    deploy:
    - provider: releases
      api_key:
        secure: bscGrBY4fO8ca32Tr35yEZuMgt7QDMydEDghvsOEhvkoTQ2piicg5QeAJDbhd1lxszLbQ/8sN0Dn08VM1GN4iWMLyZPVcf0vFAxm+8kkNr5zepjwxvOkzMv4FfnILSQEWgMIS6xTopuLxKAe7OsPGOjV/H7S+3/UOil2Av1dKx4jd93L1Q+ciERDHtDgnA6zIYqtuFe6aoiMe8TDL5/q2Xvbp6M3UJpOor64u5uuc1ruoxPewJV9NYtwP0M6JR3wMMW/chOPNRVfp2WlXPYf/U8HOThWeAhBHZNgj2pXhvvNDq8w6Z6jcHt2mb+2ot8XZAUMqllONwSKQUBagkY2frXCTB1B4BVyVkQL2N3KlpQbPfjh3yk3qU9n0o5TECSWhqxAtCe9Zk6hy5/VSQib7zmVTh74JfoEMdudHtgciEeE5BMz8aEwo0+nInQcwVI1qQkTJ/WqMHAz7UDckMsgmnPoD5xYF13tRCJBk5ctmb28uKJYd2/1CQwOHI/KzpMhWO/KgcrjFSy4J3zDFtX8v9j7ZCMtjwpnf+juMADEoYbdchfsYVPFxhdYlGIdTPfKMuvrSIxpld07RMLM6/8gRUKCNpItf7GWKGNwMOd1j5cS266nCLBjA9HoG0fE0oCEcyP3lHgWRtiD3It5hj+Fv/d2eYgRLBZyE9VVoUFvaIE=
      file: me.tar.gz
      skip_cleanup: true
  - stage: Deploy (dev)
    name: www
    node_js: '8'
    env:
    - NODE_ENV=dev
    - WWW_PACKAGE_DIR=$TRAVIS_BUILD_DIR/packages/www
    - SENTRY_ORG=randytarampi
    - SENTRY_PROJECT=www
    - SENTRY_LOG_LEVEL=debug
    - secure: BqXseN/Q6y0i7wX9eqO+3qmfNybZcOJXB1FHDa4vEfM58HvXGAzDsxc5cLn+Cv4DlZ5jBQDgPQxKz5uVPuTZI1m+Ev39S2aR9be3EGISfyShYB1SM8Mzq4vic6/gdarR7rtRMVtdU/CeZPQCXVde9NxR4oNjvDP7GwHGDsm4fjgOW7c2am70JFl26z5O2lqiw/NPQnEo45vGuIlhZaGxayn9Dy0EVHdNMYQ+2JsBXvEC0CTgAbNS8ODL223YSe3UOiN/cKOEtBOe5Sd25pu2JXHrMDWSiJnTIJRwg7VAUqNvEb+9QEGzEzKJKxSfNo7z1QnQ3JMLd8T7HJQ+TaXUr5uiOqNLHybDLumcSSghNHZQVY6+m2wFs0AwZvWHi/nPs1ld7WvlDzPVwfs8FQA3g5w07aMaVrd1O+xo0/5ZXVUkocxksLtSuXTRutwHQMbEMrbmp0uzXRH3FZvbzrmvhtbP3Kz1dO+aFC7IKaWezj5PRkdNtWPkqS+gT0IXrJnJ8gAEsRXToxEruJGwBdKkhQqQwoz7hjf8VChUOMfnOfW64/Os6yK9Grr/UyAdkf9jUL45gb8I1C16ddz6getXtrcQV/YFGkBckNnMO6SAsPci84ESlX69tlXnpLwAjf5MOpwmY/MJfX7Cd1AibzcX1rXHufPVuOdV4iSsyS+ioWY=
    install:
    - npm run postinstall
    - npm run docs --prefix packages/www
    before_script: skip
    script: skip
    after_script: skip
    before_deploy:
    - echo "dev.randytarampi.ca" > $WWW_PACKAGE_DIR/CNAME;
    - git add --verbose --force --all $WWW_PACKAGE_DIR/CNAME;
    - if [ -d "$WWW_PACKAGE_DIR/docs" ]; then ls -al $WWW_PACKAGE_DIR/node_modules/@randy.tarampi/css/node_modules/; ls -al $WWW_PACKAGE_DIR/node_modules/@randy.tarampi/css/node_modules/@fortawesome/fontawesome-free/webfonts; ls -al $WWW_PACKAGE_DIR/docs; git add --verbose --force --all $WWW_PACKAGE_DIR/docs $WWW_PACKAGE_DIR/*.html $WWW_PACKAGE_DIR/favicon.ico; fi;
    - if [[ -n $(git status -s) ]]; then git commit -m "Add assets for $TRAVIS_TAG."; fi;
    deploy:
    - provider: script
      script: git push --force https://${GH_TOKEN}@github.com/${TRAVIS_REPO_OWNER}/${TRAVIS_REPO_OWNER}.github.io.git `git subtree split --prefix packages/www`:master
      skip_cleanup: true
      on:
        branch: master
  - stage: Deploy (dev)
    name: posts
    node_js: '8'
    env:
    - NODE_ENV=dev
    - SENTRY_ORG=randytarampi
    - SENTRY_PROJECT=posts
    - SENTRY_LOG_LEVEL=debug
    - secure: BqXseN/Q6y0i7wX9eqO+3qmfNybZcOJXB1FHDa4vEfM58HvXGAzDsxc5cLn+Cv4DlZ5jBQDgPQxKz5uVPuTZI1m+Ev39S2aR9be3EGISfyShYB1SM8Mzq4vic6/gdarR7rtRMVtdU/CeZPQCXVde9NxR4oNjvDP7GwHGDsm4fjgOW7c2am70JFl26z5O2lqiw/NPQnEo45vGuIlhZaGxayn9Dy0EVHdNMYQ+2JsBXvEC0CTgAbNS8ODL223YSe3UOiN/cKOEtBOe5Sd25pu2JXHrMDWSiJnTIJRwg7VAUqNvEb+9QEGzEzKJKxSfNo7z1QnQ3JMLd8T7HJQ+TaXUr5uiOqNLHybDLumcSSghNHZQVY6+m2wFs0AwZvWHi/nPs1ld7WvlDzPVwfs8FQA3g5w07aMaVrd1O+xo0/5ZXVUkocxksLtSuXTRutwHQMbEMrbmp0uzXRH3FZvbzrmvhtbP3Kz1dO+aFC7IKaWezj5PRkdNtWPkqS+gT0IXrJnJ8gAEsRXToxEruJGwBdKkhQqQwoz7hjf8VChUOMfnOfW64/Os6yK9Grr/UyAdkf9jUL45gb8I1C16ddz6getXtrcQV/YFGkBckNnMO6SAsPci84ESlX69tlXnpLwAjf5MOpwmY/MJfX7Cd1AibzcX1rXHufPVuOdV4iSsyS+ioWY=
    - AWS_ACCESS_KEY_ID=AKIAIEKKCTFCDTGKKHMA
    - secure: HG5SiuIvZNcqaAGjaPwyQFVxW5uUfGbrN3fwqDEyh3oLW1pcnofNCNGLotWoFTexSXkPGcJeswEPfo5koRej84h1CqmNOPJNmwomjR/lLVf1/CSRY5eo4rf8no9wwEOhzsSX+r4yCyOKoBQ8iaxkcwo/fvPIEwAo1NPLcDYusm7bvAsCrO5NDpZ0KkhYqrD823UqSKLtpVAj8ZVZih3ySI+QL/cPN1LlaOwbREbSHmKvDj7p63k0F/znQ9y+jip/dRgAYreTVLOHKKQmdTLDbl0Lf6yn1m8NvC94Cl2Klt4791i/AUqrC1JV7eEE9f9n7jI3l5M469C5DWVFC9Nc9S1d2tcUAbQS441hZMsp0Hh7iLb601GSQZwI/KbNtM1hYJa/ONSrfJcWjU6MQudUHuOIZo1AoiDjlenznouRiIssJ+f3KKxK8t9UEzlTVsHSoBMvQ9lVabae7iTltM6zVD/BlirUhWFpSInSQsHOIMV1fkDep/0lfXX8rufb5pHm41A8yz3bkwLSPQILEwY9O21ngkffSKlu1sUFqvSdE6SwH5nvXEDaF44QvO9OAn3T6BRz+mHvtGCe9xwq9ixsdpEHzGcC6xHD+coJwFshByWkaMP6+RRobGwpHaxn59DGoTPWY5bhaL2EOiAQBK8d4iQg/rPM++Mcd7jDHZKnXzc=
    install:
    - npm run postinstall
    before_script: skip
    script: skip
    after_script: skip
    deploy:
    - provider: script
      script: npm run deploy --prefix packages/posts
      skip_cleanup: true
      on:
        master: true
  - stage: Deploy (prd)
    name: www
    node_js: '8'
    env:
    - NODE_ENV=prd
    - WWW_PACKAGE_DIR=$TRAVIS_BUILD_DIR/packages/www
    - SENTRY_ORG=randytarampi
    - SENTRY_PROJECT=www
    - SENTRY_LOG_LEVEL=debug
    - secure: BqXseN/Q6y0i7wX9eqO+3qmfNybZcOJXB1FHDa4vEfM58HvXGAzDsxc5cLn+Cv4DlZ5jBQDgPQxKz5uVPuTZI1m+Ev39S2aR9be3EGISfyShYB1SM8Mzq4vic6/gdarR7rtRMVtdU/CeZPQCXVde9NxR4oNjvDP7GwHGDsm4fjgOW7c2am70JFl26z5O2lqiw/NPQnEo45vGuIlhZaGxayn9Dy0EVHdNMYQ+2JsBXvEC0CTgAbNS8ODL223YSe3UOiN/cKOEtBOe5Sd25pu2JXHrMDWSiJnTIJRwg7VAUqNvEb+9QEGzEzKJKxSfNo7z1QnQ3JMLd8T7HJQ+TaXUr5uiOqNLHybDLumcSSghNHZQVY6+m2wFs0AwZvWHi/nPs1ld7WvlDzPVwfs8FQA3g5w07aMaVrd1O+xo0/5ZXVUkocxksLtSuXTRutwHQMbEMrbmp0uzXRH3FZvbzrmvhtbP3Kz1dO+aFC7IKaWezj5PRkdNtWPkqS+gT0IXrJnJ8gAEsRXToxEruJGwBdKkhQqQwoz7hjf8VChUOMfnOfW64/Os6yK9Grr/UyAdkf9jUL45gb8I1C16ddz6getXtrcQV/YFGkBckNnMO6SAsPci84ESlX69tlXnpLwAjf5MOpwmY/MJfX7Cd1AibzcX1rXHufPVuOdV4iSsyS+ioWY=
    install:
    - npm run postinstall
    - npm run docs --prefix packages/www
    before_script: skip
    script: skip
    after_script: skip
    before_deploy:
    - if [ -d "$WWW_PACKAGE_DIR/docs" ]; then ls -al $WWW_PACKAGE_DIR/node_modules/@randy.tarampi/css/node_modules/; ls -al $WWW_PACKAGE_DIR/node_modules/@randy.tarampi/css/node_modules/@fortawesome/fontawesome-free/webfonts; ls -al $WWW_PACKAGE_DIR/docs; git add --verbose --force --all $WWW_PACKAGE_DIR/docs $WWW_PACKAGE_DIR/*.html $WWW_PACKAGE_DIR/favicon.ico; fi;
    - if [[ -n $(git status -s) ]]; then git commit -m "Add assets for $TRAVIS_TAG."; fi;
    deploy:
    - provider: script
      script: git push --force https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git `git subtree split --prefix packages/www`:gh-pages
      skip_cleanup: true
      on:
        tags: true
  - stage: Deploy (prd)
    name: resume
    node_js: '8'
    env:
    - NODE_ENV=prd
    - RESUME_PACKAGE_DIR=$TRAVIS_BUILD_DIR/packages/resume
    install:
    - npm run postinstall
    - npm run docs --prefix packages/resume
    before_script: skip
    script: skip
    after_script: skip
    before_deploy:
    - git add --verbose --force --all $RESUME_PACKAGE_DIR/index.html $RESUME_PACKAGE_DIR/*.pdf $RESUME_PACKAGE_DIR/favicon.ico
    - if [[ -n $(git status -s) ]]; then git commit -m "Add assets for $TRAVIS_TAG."; fi;
    deploy:
    - provider: script
      script: $TRAVIS_BUILD_DIR/bin/split.sh resume
      skip_cleanup: true
      on:
        tags: true
  - stage: Deploy (prd)
    name: posts
    node_js: '8'
    env:
    - NODE_ENV=prd
    - SENTRY_ORG=randytarampi
    - SENTRY_PROJECT=posts
    - SENTRY_LOG_LEVEL=debug
    - secure: BqXseN/Q6y0i7wX9eqO+3qmfNybZcOJXB1FHDa4vEfM58HvXGAzDsxc5cLn+Cv4DlZ5jBQDgPQxKz5uVPuTZI1m+Ev39S2aR9be3EGISfyShYB1SM8Mzq4vic6/gdarR7rtRMVtdU/CeZPQCXVde9NxR4oNjvDP7GwHGDsm4fjgOW7c2am70JFl26z5O2lqiw/NPQnEo45vGuIlhZaGxayn9Dy0EVHdNMYQ+2JsBXvEC0CTgAbNS8ODL223YSe3UOiN/cKOEtBOe5Sd25pu2JXHrMDWSiJnTIJRwg7VAUqNvEb+9QEGzEzKJKxSfNo7z1QnQ3JMLd8T7HJQ+TaXUr5uiOqNLHybDLumcSSghNHZQVY6+m2wFs0AwZvWHi/nPs1ld7WvlDzPVwfs8FQA3g5w07aMaVrd1O+xo0/5ZXVUkocxksLtSuXTRutwHQMbEMrbmp0uzXRH3FZvbzrmvhtbP3Kz1dO+aFC7IKaWezj5PRkdNtWPkqS+gT0IXrJnJ8gAEsRXToxEruJGwBdKkhQqQwoz7hjf8VChUOMfnOfW64/Os6yK9Grr/UyAdkf9jUL45gb8I1C16ddz6getXtrcQV/YFGkBckNnMO6SAsPci84ESlX69tlXnpLwAjf5MOpwmY/MJfX7Cd1AibzcX1rXHufPVuOdV4iSsyS+ioWY=
    - AWS_ACCESS_KEY_ID=AKIAIEKKCTFCDTGKKHMA
    - secure: HG5SiuIvZNcqaAGjaPwyQFVxW5uUfGbrN3fwqDEyh3oLW1pcnofNCNGLotWoFTexSXkPGcJeswEPfo5koRej84h1CqmNOPJNmwomjR/lLVf1/CSRY5eo4rf8no9wwEOhzsSX+r4yCyOKoBQ8iaxkcwo/fvPIEwAo1NPLcDYusm7bvAsCrO5NDpZ0KkhYqrD823UqSKLtpVAj8ZVZih3ySI+QL/cPN1LlaOwbREbSHmKvDj7p63k0F/znQ9y+jip/dRgAYreTVLOHKKQmdTLDbl0Lf6yn1m8NvC94Cl2Klt4791i/AUqrC1JV7eEE9f9n7jI3l5M469C5DWVFC9Nc9S1d2tcUAbQS441hZMsp0Hh7iLb601GSQZwI/KbNtM1hYJa/ONSrfJcWjU6MQudUHuOIZo1AoiDjlenznouRiIssJ+f3KKxK8t9UEzlTVsHSoBMvQ9lVabae7iTltM6zVD/BlirUhWFpSInSQsHOIMV1fkDep/0lfXX8rufb5pHm41A8yz3bkwLSPQILEwY9O21ngkffSKlu1sUFqvSdE6SwH5nvXEDaF44QvO9OAn3T6BRz+mHvtGCe9xwq9ixsdpEHzGcC6xHD+coJwFshByWkaMP6+RRobGwpHaxn59DGoTPWY5bhaL2EOiAQBK8d4iQg/rPM++Mcd7jDHZKnXzc=
    install:
    - npm run postinstall
    before_script: skip
    script: skip
    after_script: skip
    deploy:
    - provider: script
      script: npm run deploy --prefix packages/posts
      skip_cleanup: true
      on:
        tags: true
notifications:
  slack:
    secure: MTSym0Ymg+oYMx+Fmf3a2g2LyVtPJ8hg4sjtbfdyPBZAhO3rU9RxRFrBimNp9knZppwFpofosW4C6bKEBAN6p2AfeZOqQmYuRetZdS27pO6mdBpH56EJ7o2VJS/5ec9Lqw77802FO8XiRtWwySvxyE9nEHmm5dxOYf2JYj9OTiyNqmyRJFTRQiURZLOxn1CJLUI3OB8A0dtRU1hI3xx0kP+q7fHXp8xdNssB8ETBXwzG3HFE12VQRseCe01U0PdmGiRwQRQGXcGg00KTPFU1Gin7LY9mhSHRV9TsmvTtx6gXMYHo2UiLts0Omeb80k1nDZwBcAYsY4bIpgI1e01jJpDIHbg4lWskbnnSZWHG9QPIsOcG236Oqz/5bj+J70gRMw1zu+UYnH8XcfgcV+tBOu86oj8rtWeFGr58mh1HOiNedvqef2xNi+Yc3Ykj3ZfjVITlI/Lfpi6ZPNhjpL4Bbanmyd3KbbaYpdWkY5+SYJOhidq6VpHpBIqsACUwsLl6X8Yajteh5TLMK9ixkaTL97BT8niHTtEwkraMs5a0yfi9EDQNOjFERJq48Jrhpuq+MosgmyMmgX+31khzIgMr9+AUy3wL3dmIO198+Wm/k2rElYJmYuORI+txzIwYDGsaUbusyhy578Q5ilsiLbF1jZnPrvlQKVLCTIAMlXdmTpw=
