language: python

python:
- "3.5"

env:
- CXX=g++-4.8
- TRAVIS_NODE_VERSION=6

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
- touch .env
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

install:
- pip install -r requirements.txt
- npm install

#script: npm run travis
script: echo "Lol. Just straight up deploying..."

before_deploy:
- touch .env
- mkdir -p ../dpl_cd_upload
- tar -zcf ../dpl_cd_upload/me.blog.tar.gz -C ./ .

deploy:
- provider: s3
  access_key_id: AKIAI3EMH5UQ2CYHR3SA
  secret_access_key: &1
    secure: hZ/yQMJFWwFCqp67c4fysofF9Iz5Fs1tl9ckP+CPR6jWdXrSjvEwV+d83EyK2ExCC0LNolYKZLpCNZmyfRlSkwE2Bo8Pf6x63WNzTCBMMLjpup1H1sUvG1X0BEC2pp76GkoSoLd2LQSSJUTrYlDIzue8hgGmrr/pszGyNUJwoRAfm1LM3UkHFCYC9WmlZnqYZT8IUzxMcQ1+rGqkbgd6AcQPCb7UdMbzJntHqE1yYnQhJlMTzKg4ZxIsIUS+qHfihzyt2ocBTii0THQ8BnNt4W1B5bcc2l3IBf0bf2ZwNSrAXJy6sX9/+9aR+3N3bXA05mdUFy08klOpKENZGnA9QIxGydjT1KrRV6OE+Y6qIzypJm0rAmQMx+tQtJ5O5BUw2U3jevUSurnjuIEPwWwvBisRMKbEEu7Aeuu7bMJ0HkdwGpWzUl6NesyfrcbKLQFioWUEpUfTMOUvt3ytdPZQ3BbaX3OE5Ty0oORbfh6zecBk0M5jdZWwN47+HvZN+J+w87K+BTh67qHmpoQDYNx+1tzttQ9k2rbizui3zetqtrv7OLoi2Ya/AobLacYp+vvdZ3fjgquZsbhuEJrdIMMM1E8LzfcrzXbCrJMEAQIkGIPt03t9bqdPtYNZcZp3tZcvhzNAIYTPj2qX8TwHpOSzSZ3hs3wiOB1V9WV11F5YVaw=
  skip_cleanup: true
  on: &2
    repo: randytarampi/me.blog
    branch: master
  bucket: randytarampi-releases
  region: eu-west-1
  detect_encoding: true
  local-dir: ../dpl_cd_upload
- provider: codedeploy
  access_key_id: AKIAI3EMH5UQ2CYHR3SA
  secret_access_key: *1
  bucket: randytarampi-releases
  key: me.blog.tar.gz
  bundle_type: tgz
  application: me.blog
  deployment_group: web
  on: *2
  wait-until-deployed: true
  region: eu-west-1
