language: node_js
dist: trusty
node_js:
- '8'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAIEKKCTFCDTGKKHMA
  - secure: tfQPXRzAFd9URzy93seq5KAo9i19tV8g+JC/hULQwYPADDV6vvB+GM0A6x/CyOQ1MIrtik60r9LgRLk0xoJzCh4b2NM65fTNzfdEbp8cfZDd1KLESW4vC4643O9SF0/UcXIp/ITaWBYZ65zkHMZ5QQuEAk1dqzcXyuTXICL6prGWRdvXT8P1FVCr7GqnVFby5ZX3G9Q5E4SaP323yTnfObPcvBibh/9T0lSu6sPfTIUDJIV46ckyBn0EyM1A0Niw7PI7grhMiNElqjBDIcH1qR9Yl8+XQEZtN2gBey3HNjV8qXN0g7FuccZIybjL80R4274P4jGB8jp276cQJl/OJOBSNbd1DoLlq3skXkBqqGFHQMxOG2ZGh2Xp7o5Q0ao3upp8bdcI08ERqX+v7hrW3g0liDogO4SFjPyAOKXS7YWCDNCKBKq8lDRpCUk8V/qJzfeJuT8/c+nzSXCRG/LJlwpzayKV9PK4d5yVILtoTxi7r22a5Oa5BVOL9ZpqOy5EE5abbu0ELjHlRcQ41o6efCJO3QGsUtBMU4Sx4DAZ5+YRsohFh55JZkjrIX1oimfRjPLf/PzvNg/8BkCXDw6a0NzVzIoeP/kOexethB/kUo81/ttXuNmurNoNyCIcGTR2j6DKljRDUZE33xv9ND3HQGLhrxVR1uwA1H6ERgHbbfI=
  - secure: 05yEJUu6Xwi7xqlXuPlzKbF7tiQj1HhHAfg3pyJb29uScHM5J26Rdj2g7nR7sCbXlr3z41hB0v0w1vcKv6BdEgv1dW0wfP46l0q1CrVfwVlc63AwG+5aF4p+A/7ppRC+23Ba+fOi3bPVqIxHi2VWum0sHBphe3ZElymp5D3PiCwBGJYZUnNssvrz8nHwKoTjNqVVxogsH/aGUg60BRa9O+MMGWqgXjaKDdG/TjBbWZpBIJN7xDnAzDKOtTmdf4JVnhxaL3XgryXujCRWQGX9PBkGSczwu+6hAoaneQStZav1Gn3nEbyGfXoLhLsOZ/M3ERSqcYqOZIM3NU9KpFC49Ew13/xKkmjSPud9JLSqWCzzzV+fwLEP9QrHE9gEWj11Ul4bb+mZ8V7L0spCOURQ+t0E1JnsYT9b3VqH34Q7ENrWARG0fODyi/wYCmoIRPKee9a+BUddmFYbW4LoCulEx3auXpGM+18a3H/Qv9isAUi/bi1QwoFq2qL8iQHVuswqGr+Kcv6sEshf7m/nzxnXOOudVXpdAcm85/nukQlxIdnloeDC/systdFnK5THvSjYgFWnVr+mp8GJ6caYRszjLJmJKUIC88nF7V4sBKDVrrYy8hKLBKxus9a312QvNLxvgUsFkucU2bg7fZl/Lsj2xztWZfBt5FuWUXrm3Z4zDog=
before_install:
- uname -a
- lscpu
- npm install -g npm
- npm install -g serverless
- export NODE_ENV=prd;
script: npm test
after_success:
- mkdir -p ../dpl_cd_upload
- tar -zcf ../dpl_cd_upload/me.posts.tar.gz -C ./ .
- git config --local user.name "Travis"
- export TRAVIS_AUTHOR=travis@randytarampi.ca
- export COMMIT_AUTHOR=`git --no-pager show -s --format='%ae' \`git rev-parse\``
- git config --local user.email $TRAVIS_AUTHOR
- if [ -z "$TRAVIS_TAG" ]; then if [ "$COMMIT_AUTHOR" != "$TRAVIS_AUTHOR" ]; then
  npm version minor; git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} --tags;
  npm version preminor -m "[Travis] Prepare version %s"; git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}
  HEAD:master; fi; fi;
deploy:
- provider: script
  script: NODE_ENV=dev npm run deploy
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: NODE_ENV=prd npm run deploy
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: g0wMZBg1xSjZZGIneSZMyvpPMX+js/Fi0Ny2onu8qfb5Fy1pPiKiwvOKjHFVg6F3D4/ZBxGfHieQ3SMyQCFegebEYL/lcUw766B90C1Vk2/5vTqL8CJsnPM7n+rZgERW5vWAQ3/zbcW3Qt8F0u/A7vu5YpY5jgKXlTqfsE4Aq85d0yqcFkO8IqWL7i3EsIXrS06M8N5vN2zZpSqyQV6Jm0Ph5lw3udG+Z745q6n9Ki9TPAxNcLwlr3hNKyngm9yXE5RjEGdNPYNuEy90vSGxzujbRNa7nY0Nr5m81cqnX9XT1NlizMj6tkvbNP4T6X8BG8dasiGMSYK3h4tyZW09Gp/ECDpTgHYIOocsReZ8kcbTDvUvCz7sslqRnDFoO8YmJnK+FwtG3nkGC3a4kNDkgJnoLYvmyB60Z/wszaxhZ6ygWutEnA8ZLy3axm7NRFdqURLiBheCTCWh4pqZ+FV2EpT+o1kAeFLu02S/OVHNY2VV5/DPvtYN4Mt+v9EaJJ6bmKmB2VpebpdTDv8vcYySJ364e9doRhXKbVp1Elnl9nduuwW8D1wp+Yh5rCgaYD6Ta6E73QPcZ3y/cP6pLTJ+k0ZeU9nmGGPS8j4plXBsBLjfuF3bbp9VmZzdqapVOsEgK/RmSWKfvtJaCrAaJcA/RG4OXQ4F4O35QDxoYGf0Io0=
