language: node_js
dist: trusty
node_js:
- '8'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAIEKKCTFCDTGKKHMA
  - secure: QIva2vVGJy+Qu8+tHelYC15YjWlSseWf0usaJvnJLq3Ep6NZEaQc2vTxCnyHSejuAnhhYxPB/65TRPEv4FN8Mg7jszH7YJ97UBu4+wR4gkdka/v51NYH+gb0Z9Z2HVucjA8VpGC35/h5HMdjT8PTKAyEQX4NNcHmuNrefPVZwhjUzgkFjtbTlTO5ViJEuv4ZKY+nVzzx3+9oFuFqJysAfD7cL5UjOgbti8Eojy2sC9tT6Mt1RGwviMmK14ww2Fda29Z3Oztsh3vILDRE0soGes7crQk2vqWygabkNVyaFgeDXR+mlsnp0b4W24MOC0Y7OzZBnubvEFHknjqOF9idyHsVv0S0IDNzzCf5mBCkuFkkF00xnIcTEoLLkFlH0oOhH3KM8T94l4h2Quqh7B0wdYu/25wUyeVymDqnnxOg/Sx4kZWS7Qqp09YAezDyi1DpqNFSlfWE7pdlQ6I51C0UkheuWaWCMNqyLi7kRRYyzd6m4kYamWv2H5VbqRCqKsz/tPafCe6jTTc+fjRLH53Lxk2sjxOVwWMSlDDOkK3O9jmp5bKgtafSBGO8Gn8iCtMLXYWN30odUiXkXqyvZvob7foOZa7toLMK48ZTgfrwkIraDTb8bx2WznG9jvJneeUMSz3NjiTlATK2N0OfyBoMk/Dq94lakN2BEegMXZIPNus=
  - secure: 5TZ7A/kX5KIt25D5lMvuPXG44n6Z8ioWMRm/fZKvCk+RdqUsMpuvxOBmtaQfWNTUOQFxKW9OglZv/gEM67JNZfX5tRDuUW+LptkS+zsdUJPBmh4gqX5sUvDMII6zh3Uv5op288uvGjkz/h8bjxZovSP79BlzDFO2UixepqBkO/osLejN4fgBiAXKcxoWA09mHgEddgAEghskmOLBLaQsvYQ8/svukBrbz07rWSGxxmY1OOLrFd2I74kBPBX2DCN3fRAUbi5vFKaeGYpO4xDgd7JiTCz4zA4EBPGX1CdSSz1cwgLw7MbtYzHuKOD7oMNYChWHyb7Rkj2NT7OlE+/50b4RmZQuKG0HkUt0iFAxEEgJzTrqty+7MhUU16BJNcbJUQ1uuf4apevaEopQa94jMxlet+OUWiLwsPJaJIAPeJAM8oONm1Hf69gCrTyYk9TYdJkO5vMKPZbWw7lAHZf1KKoS8cxJ9L+rnYgoL0OdE/tYHpayVT1LO0PmA0awNj/Cc3UxmOP5ANR+o5jVZPOAKXknAoqzYnZr/R7h9oraGMwKjvsi358aQKkfwwzsYSXeCFhaZhib6jaC/q+euC1alf4Yggc6IE+Vvu7P0GrSq9bzPykhNemPhBzO08OiV521EHdEVSJyT5I/q1h8yv1uz/pJpZkz03R/4P+n1tgK7AY=
before_install:
- uname -a
- lscpu
- npm install -g npm
- npm install -g serverless
- export NODE_ENV=prd;
script: npm test
after_success:
- mkdir -p ../dpl_cd_upload
- tar -zcf ../dpl_cd_upload/me.posts.tar.gz -C ./ .
- git config --local user.name "Travis"
- export TRAVIS_AUTHOR=travis@randytarampi.ca
- export COMMIT_AUTHOR=`git --no-pager show -s --format='%ae' \`git rev-parse\``
- git config --local user.email $TRAVIS_AUTHOR
- if [ -z "$TRAVIS_TAG" ]; then if [ "$COMMIT_AUTHOR" != "$TRAVIS_AUTHOR" ]; then
  npm version minor; git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} --tags;
  npm version preminor -m "[Travis] Prepare version %s"; git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}
  HEAD:master; fi; fi;
deploy:
- provider: script
  script: NODE_ENV=dev npm run deploy
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: NODE_ENV=prd npm run deploy
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: g0wMZBg1xSjZZGIneSZMyvpPMX+js/Fi0Ny2onu8qfb5Fy1pPiKiwvOKjHFVg6F3D4/ZBxGfHieQ3SMyQCFegebEYL/lcUw766B90C1Vk2/5vTqL8CJsnPM7n+rZgERW5vWAQ3/zbcW3Qt8F0u/A7vu5YpY5jgKXlTqfsE4Aq85d0yqcFkO8IqWL7i3EsIXrS06M8N5vN2zZpSqyQV6Jm0Ph5lw3udG+Z745q6n9Ki9TPAxNcLwlr3hNKyngm9yXE5RjEGdNPYNuEy90vSGxzujbRNa7nY0Nr5m81cqnX9XT1NlizMj6tkvbNP4T6X8BG8dasiGMSYK3h4tyZW09Gp/ECDpTgHYIOocsReZ8kcbTDvUvCz7sslqRnDFoO8YmJnK+FwtG3nkGC3a4kNDkgJnoLYvmyB60Z/wszaxhZ6ygWutEnA8ZLy3axm7NRFdqURLiBheCTCWh4pqZ+FV2EpT+o1kAeFLu02S/OVHNY2VV5/DPvtYN4Mt+v9EaJJ6bmKmB2VpebpdTDv8vcYySJ364e9doRhXKbVp1Elnl9nduuwW8D1wp+Yh5rCgaYD6Ta6E73QPcZ3y/cP6pLTJ+k0ZeU9nmGGPS8j4plXBsBLjfuF3bbp9VmZzdqapVOsEgK/RmSWKfvtJaCrAaJcA/RG4OXQ4F4O35QDxoYGf0Io0=
