language: node_js
node_js:
- '6'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- touch .env
script: npm run travis
before_deploy:
- mkdir -p ../dpl_cd_upload
- tar -zcf ../dpl_cd_upload/me.photos.tar.gz -C ./ .
deploy:
- provider: s3
  access_key_id: AKIAI3EMH5UQ2CYHR3SA
  secret_access_key: &1
    secure: NwZuFhzS+WXalDh9yIIL1Q/q2sAxhe0tzrNl3I7uYQahpStQO2UPWgmK2GQt76/8Un+irdzUAlqgTpxBr3CLaac5bVm6ZH+XZAKnao4kfTkwTBaWHNJ5C0+AXwWjSy1rxwyveVTKWHrgv07GdV+0NJ0UEYEL84vDFsHXexRbq8ceZkf8gvuMgbnAqbvaxp23DfEjkyE4mUUaX+phRsnJaty/Ujk5LlGUO5KCcm2G+NA6fpcBp4pb+dJwbEGBf3sgE1GDiVzMGXgql+OTKFHiliGojUfp3LZKih2EjNTUdutUJgxcxvM2KooxG5IXHOFK6ZWIG5ehOnJwz7DjZDfocS0a5NpMTqnXES2FpCyconpe0TTQBWrmXbvHtN8N9Nsdn7SpvX7J0LZ4GINs07wQ6h1bTxkd9bgie8w7UfjLY/Q8nMnUNZMnQRt/9GmSirjZvu8MVIR9WZrX5aT0vNIW2qio3TwivNFQoisdHPA9lTIwkSBH8FJ46K++UZY59FPI/rgwZEIiUcdSQigVEd9u3ABQmH8Z92jCmDQWxwviJnJ5Xxi06rIvxQnbTLAaLeYVKUL7u4GRhMHjZUMbpncZ4uQeZJDQRs2VQ7WDQwNLJD3k5zSKzzHFfwWZBSP7cTczznE87Xf/SMoAcTxIiGMOvbIfvdsM1NzkibxixISXbfc=
  skip_cleanup: true
  on: &2
    repo: randytarampi/me.photos
    branch: master
  bucket: randytarampi-releases
  region: eu-west-1
  detect_encoding: true
  local-dir: ../dpl_cd_upload
- provider: codedeploy
  access_key_id: AKIAI3EMH5UQ2CYHR3SA
  secret_access_key: *1
  bucket: randytarampi-releases
  key: me.photos.tar.gz
  bundle_type: tgz
  application: me.photos
  deployment_group: web
  on: *2
  wait-until-deployed: true
  region: eu-west-1
