
version: 0.0
os: linux

files:
  - source: /
    destination: /opt/randytarampi/me.photos/app/

hooks:
  ApplicationStop:
    - location: bin/stop
      timeout: 60
  BeforeInstall:
    - location: bin/cleanup
      timeout: 60
  ApplicationStart:
    - location: bin/start
      timeout: 60
