photosServiceUrl: http://localhost:3006/posts?type=Photo
postsServiceUrl: http://localhost:3006/posts
wordsServiceUrl: http://localhost:3006/posts?type=Post
codeAppUrl: /code
photosAppUrl: /photos
postsAppUrl: /blog
wordsAppUrl: /words
resumeAppUrl: /resume
letterAppUrl: /letter
assetUrl: ""
gtm: "GTM-K26GTD2"
sentryDsn: https://5f246bd3456d477da7ebf2d4fd06f2bb@sentry.io/1240735
resume:
  publishUrl: https://www.randytarampi.ca/resume
letter:
  publishUrl: https://www.randytarampi.ca/letter
logger:
  enabled: true
  streams:
    stdout: false
    sentry: false
    human: true
    console: true
  level: trace
  src: true
me:
  basics:
    name: Randy Tarampi
    label: Going places | building software
    picture: https://secure.gravatar.com/avatar/2efab7e328dae90b9ff272f9ee4974b8?s=512
    email: jobs@randytarampi.ca
    phone: "+1 (604) 374-7128"
    website: https://www.randytarampi.ca
    summary: Just another code monkey looking to broaden his skillset and horizons, preferably
      outside of North America. Prefers fitness balls over fancy chairs and better known
      in person than on paper or screen
    location:
      address: 4663 Todd Street
      postalCode: V5R 3P7
      city: Vancouver
      countryCode: CA
      region: BC
    profiles:
    - network: GitHub
      username: randytarampi
      url: https://github.com/randytarampi
    - network: Instagram
      username: randytarampi
      url: https://instagram.com/randytarampi
    - network: LinkedIn
      username: randytarampi
      url: https://linkedin.com/in/randytarampi
    - network: Flickr
      username: randytarampi
      url: https://www.flickr.com/people/randytarampi
    - network: AngelList
      username: randytarampi
      url: https://angel.co/randytarampi
    - network: StackOverflow
      username: randytarampi
      url: https://stackoverflow.com/story/randytarampi
  campaign:
    source: ""
    medium: ""
    name: ""
    term: ""
    content: ""
