photosServiceUrl: http://localhost:3006/photos
postsServiceUrl: http://localhost:3006/posts
wordsServiceUrl: http://localhost:3006/words
codeAppUrl: /code
photosAppUrl: /photos
postsAppUrl: /blog
wordsAppUrl: /words
resumeAppUrl: /resume
assetUrl: ""
gtm: "GTM-K26GTD2"
sentryDsn: https://62e5366a2fdd43598035164511e5e986@sentry.io/1240797
resume:
  publishUrl: http://www.randytarampi.ca/resume
