posts:
  photosUrl: https://posts.dev.randytarampi.ca/posts?type=Photo
  postsUrl: https://posts.dev.randytarampi.ca/posts
  wordsUrl: https://posts.dev.randytarampi.ca/posts?type=Post
  resumeUrl: https://raw.githubusercontent.com/randytarampi/me/master/packages/resume/resumes
  letterUrl: https://raw.githubusercontent.com/randytarampi/me/master/packages/letter/letters
resume:
  publishUrl: https://dev.randytarampi.ca/resume
letter:
  publishUrl: https://dev.randytarampi.ca/letter
www:
  assetUrl: /docs
gtm: "GTM-T3FHTVC"
logger:
  streams:
    stdout: true
    sentry: true
    human: false
    console: true
  level: debug
  src: true
