photosServiceUrl: https://posts.dev.randytarampi.ca/photos
postsServiceUrl: https://posts.dev.randytarampi.ca/posts
wordsServiceUrl: https://posts.dev.randytarampi.ca/words
assetUrl: /docs
resume:
  publishUrl: https://dev.randytarampi.ca/resume
letter:
  publishUrl: https://dev.randytarampi.ca/letter
gtm: "GTM-T3FHTVC"
