posts:
  photosUrl: https://posts.dev.randytarampi.ca/posts?type=Photo
  postsUrl: https://posts.dev.randytarampi.ca/posts
  wordsUrl: https://posts.dev.randytarampi.ca/posts?type=Post
  resumeUrl: https://raw.githubusercontent.com/randytarampi/me/master/packages/resume/src/resumes
  letterUrl: https://raw.githubusercontent.com/randytarampi/me/master/packages/letter/src/letters
www:
  publishUrl: https://dev.randytarampi.ca
  assetUrl: &wwwAssetUrl ""
resume:
  publishUrl: https://dev.randytarampi.ca/resume
  assetUrl: *wwwAssetUrl
letter:
  publishUrl: https://dev.randytarampi.ca/letter
  assetUrl: *wwwAssetUrl
gtm: "GTM-T3FHTVC"
crisp: "03689d2b-80ab-4f5d-90cb-a2de269ea9c3"
logger:
  streams:
    stdout: true
    sentry: true
    human: false
    console: true
  level: debug
  src: true
