photosServiceUrl: https://posts.randytarampi.ca/posts?type=Photo
postsServiceUrl: https://posts.randytarampi.ca/posts
wordsServiceUrl: https://posts.randytarampi.ca/posts?type=Post
resumeServiceUrl: https://raw.githubusercontent.com/randytarampi/me.resume/master/resumes
assetUrl: /docs
gtm: "GTM-W6NFL6M"
logger:
  streams:
    stdout: true
    sentry: true
    human: false
    console: true
  level: info
  src: false
