photosServiceUrl: https://posts.randytarampi.ca/posts?type=Photo
postsServiceUrl: https://posts.randytarampi.ca/posts
wordsServiceUrl: https://posts.randytarampi.ca/posts?type=Post
assetUrl: /docs
gtm: "GTM-W6NFL6M"
