posts:
  photosUrl: https://posts.randytarampi.ca/posts?type=Photo
  postsUrl: https://posts.randytarampi.ca/posts
  wordsUrl: https://posts.randytarampi.ca/posts?type=Post
  feedUrl: https://posts.randytarampi.ca/posts/feed.rss
  resumeUrl: https://raw.githubusercontent.com/randytarampi/me/master/packages/resume/src/resumes
  letterUrl: https://raw.githubusercontent.com/randytarampi/me/master/packages/letter/src/letters
www:
  publishUrl: https://www.randytarampi.ca
  assetUrl: &wwwAssetUrl ""
resume:
  publishUrl: https://www.randytarampi.ca/resume
  assetUrl: *wwwAssetUrl
letter:
  publishUrl: https://www.randytarampi.ca/letter
  assetUrl: *wwwAssetUrl
gtm: "GTM-W6NFL6M"
crisp: 7b5aa3db-d25f-4abf-9d9d-85f62d9c1428
logger:
  streams:
    stdout: true
    sentry: true
    human: false
    console: true
  level: info
  src: false
