gtm:
  container:
    id: ""
ga:
  property:
    id: ""
mixpanel:
  app:
    id: ""
crisp:
  app:
    id: ""
sentry:
  dsn: https://5f246bd3456d477da7ebf2d4fd06f2bb@sentry.io/1240735
resume:
  publishUrl: https://www.randytarampi.ca/resume
  assetUrl: http://localhost:3004
letter:
  publishUrl: https://www.randytarampi.ca/letter
  assetUrl: http://localhost:3002
www:
  publishUrl: https://www.randytarampi.ca
  assetUrl: http://localhost:3000
