# NOTE-RT: a `.gitignore`d file to facilitate easy uploading and downloading of secrets from some `.secrets.<AWS Region>.yml`

f00px-api-key: # By default, the key here will map to the key's name in the parameter store
  # Object values' keys map directly to `sls secrets set` options per https://github.com/trek10inc/serverless-secrets#serverless-secrets-set-parameters.
  description: This is some 500px key that's unused
  text: EXAMPLE-KEY
f00px-api-secret: EXAMPLE-KEY # String values will be assumed to be a text value to be encrypted
flickr-api-key: # Equivalent to the `f00px-api-secret` example
  text: EXAMPLE-KEY
flickr-api-secret:
  name: SOME-OTHER-PARAMETER-STORE-NAME-THAN-FLICKR-API-SECRET
  text: EXAMPLE-KEY
unsplash-api-key:
  file: SOME-FILE-WITH-CREDENTIALS
unsplash-api-secret: EXAMPLE-KEY
instagram-access-key: EXAMPLE-KEY
instagram-api-secret: EXAMPLE-KEY
instagram-api-token: EXAMPLE-KEY
tumblr-api-key: EXAMPLE-KEY
tumblr-api-secret: EXAMPLE-KEY
sentry-dsn: EXAMPLE-KEY
